### PR TITLE
Money::ratioOf throws exception if currencies don't match

### LINKED ISSUE #732: ratioOf works incorrect for currencies with different minor units
`ratioOf` assumes that the given amount has the same minor units as the current amount, otherwise the result is incorrect:

```php
Money::EUR(20_00)->ratioOf(Money::JPY(1000))
```
expected: 0.02
actual: 2.00

Probably `ratioOf` should throw an exception when currencies don't match to avoid unexpected results.

### PR DESCRIPTION
**Pull request by peterdevpl**
I also added a test case for `Money::mod` which already performs currency check.

fixes #732

### CODE REVIEW

File: tests/MoneyTest.php [hunk 1]
```diff
@@ -315,6 +329,20 @@ public function itThrowsWhenCalculatingRatioOfZero(): void
...
+     */
+    public function itThrowsWhenCalculatingRatioOfDifferentCurrencies(): void
+    {
+        $money      = new Money(self::AMOUNT, new Currency(self::CURRENCY));
+        $rightMoney = new Money(self::OTHER_AMOUNT, new Currency(self::OTHER_CURRENCY));
+
+        $this->expectException(InvalidArgumentException::class);
+
+        /** @psalm-suppress UnusedMethodCall this method throws */
+        $money->mod($rightMoney);
```
Comment (smelesh) [inline tests/MoneyTest.php:343]: it looks like `ratioOf` should be there

**Review by smelesh — CHANGES_REQUESTED** [review]

File: tests/MoneyTest.php (hunk 1 above)
Comment (peterdevpl) [reply tests/MoneyTest.php]: Good catch, fixed!

**Comment by frederikbosch** [comment]
Nice catch, will merge when green checks. Thanks!
