### PR TITLE
Formatter and parser review

### LINKED ISSUE #208: Throw ParseException in StringToUnitParser

### PR DESCRIPTION
**Pull request by frederikbosch**
- Bitcoin formatter and parser only format and parse their own currency
- added FormatterException
- added Aggregate Formatter and Aggregate Parser
- StringToUnitsParser now throws ParserException

Fixes #208, #205 and #211.

### CODE REVIEW

File: spec/Formatter/AggregateMoneyFormatterSpec.php [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+use Money\Exception\FormatterException;
+use Money\Money;
+use Money\MoneyFormatter;
+use PhpSpec\ObjectBehavior;
+
+class AggregateMoneyFormatterSpec extends ObjectBehavior
+{
+    function it_is_initializable(MoneyFormatter $moneyFormatter)
+    {
+        $this->beConstructedWith([
```
Comment (sagikazarmark) [inline spec/Formatter/AggregateMoneyFormatterSpec.php]: This should go into a let method (see other specs) which is the same as setUp in PHPUnit.

File: spec/Formatter/AggregateMoneyFormatterSpec.php [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+        ]);
+
+        $money = new Money(1, new Currency('USD'));
+
+        $this->shouldThrow(FormatterException::class)->duringFormat($money);
+    }
+
+    function it_uses_default_when_no_specific_found(MoneyFormatter $moneyFormatter1, MoneyFormatter $moneyFormatter2)
+    {
+        $this->beConstructedWith([
```
Comment (sagikazarmark) [inline spec/Formatter/AggregateMoneyFormatterSpec.php]: This can remain here. You can have multiple construction. In this case the one in the let method will be the default, and this one will override it.

File: spec/Formatter/BitcoinMoneyFormatterSpec.php [hunk 3]
```diff
@@ -30,7 +31,7 @@ function it_is_a_money_formatter()
      */
     function it_formats_money($value, $formatted, $fractionDigits, MoneyFormatter $moneyFormatter)
     {
-        $this->beConstructedWith($moneyFormatter, $fractionDigits);
+        $this->beConstructedWith($fractionDigits);
 
         $moneyFormatter->format(Argument::type(Money::class))->shouldNotBeCalled();
```
Comment (sagikazarmark) [inline spec/Formatter/BitcoinMoneyFormatterSpec.php]: We don't need this anymore.

File: src/Formatter/AggregateMoneyFormatter.php [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+
+/**
+ * Formats a Money object using other Money formatters.
+ *
+ * @author Frederik Bosch <f.bosch@genkgo.nl>
+ */
+final class AggregateMoneyFormatter implements MoneyFormatter
+{
+    /**
+     * @var array|MoneyFormatter[]
```
Comment (sagikazarmark) [inline src/Formatter/AggregateMoneyFormatter.php]: IMO `MoneyFormatter[]` is enough

File: src/Formatter/AggregateMoneyFormatter.php [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+     */
+    private $formatters = [];
+
+    /**
+     * @param array|MoneyFormatter[] $formatters
+     */
+    public function __construct(array $formatters)
+    {
+        foreach ($formatters as $currencyCode => $formatter) {
+            if ($formatter instanceof MoneyFormatter === false) {
```
Comment (sagikazarmark) [inline src/Formatter/AggregateMoneyFormatter.php]: Yoda condition

File: src/Parser/AggregateMoneyParser.php [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+    {
+        foreach ($this->parsers as $parser) {
+            try {
+                return $parser->parse($money, $forceCurrency);
+            } catch (Exception\ParserException $e) {
+            }
+        }
+
+        throw new Exception\ParserException(
+            sprintf('Unable to parse %s', $money)
```
Comment (sagikazarmark) [inline src/Parser/AggregateMoneyParser.php]: What if money is not string? This will trigger an error.

**Comment by sagikazarmark** [comment]
Looks good. Added a few comments.

**Comment by frederikbosch** [comment]
@sagikazarmark Thanks for the review. Improved the code based on your remarks.

File: spec/Formatter/BitcoinMoneyFormatterSpec.php [hunk 7]
```diff
@@ -30,7 +31,7 @@ function it_is_a_money_formatter()
      */
     function it_formats_money($value, $formatted, $fractionDigits, MoneyFormatter $moneyFormatter)
```
Comment (sagikazarmark) [inline spec/Formatter/BitcoinMoneyFormatterSpec.php]: Neither the moneyFormatter argument

Comment (frederikbosch) [inline spec/Formatter/BitcoinMoneyFormatterSpec.php]: Has been removed now.

File: src/Parser/BitcoinMoneyParser.php [hunk 8]
```diff
@@ -39,8 +33,12 @@ public function __construct(MoneyParser $innerParser, $fractionDigits)
      */
     public function parse($money, $forceCurrency = null)
     {
+        if (!is_string($money)) {
+            throw new ParserException('Money should be a string');
```
Comment (sagikazarmark) [inline src/Parser/BitcoinMoneyParser.php]: Hm, maybe we could improve this text a little. Money usually refers to the object or the amount. Maybe unformatted/raw money should be string?

Comment (frederikbosch) [inline src/Parser/BitcoinMoneyParser.php]: Also done. Good idea. Included an example.

**Comment by frederikbosch** [comment]
After Travis is alright, I am merging this in.
