### PR TITLE
Fixes #227.

### LINKED ISSUE #227: Money does not allow values higher than PHP_INT_MAX
This does not work, while it should.

```php
(new Money(PHP_INT_MAX, new Currency('EUR')))->add(new Money(1, new Currency('EUR')))
```

Cause.
```php
filter_var($amount, FILTER_VALIDATE_INT) === false
```

Apparently, `filter_var` does have `PHP_INT_MAX` as its upper boundary. So we should validate with another method. Of course, regular expressions will work, but I wonder if there is not a faster method.

### PR DESCRIPTION
**Pull request by frederikbosch**

### CODE REVIEW

File: src/Number.php [hunk 1]
```diff
@@ -157,4 +157,25 @@ public function getIntegerRoundingMultiplier()
...
+     *
+     * @return bool
+     */
+    public static function isInteger($number)
+    {
+        if (filter_var($number, FILTER_VALIDATE_INT) !== false) {
+            return true;
+        }
+
+        $invalid = array_filter(
```
Comment (sagikazarmark) [inline src/Number.php]: Not sure this is the fastest, but we can improve that if necessary without breaking API. I will try to write some benchmarks.

File: tests/MoneyTest.php [hunk 2]
```diff
@@ -26,4 +27,13 @@ public function testJsonEncoding()
             json_encode(Money::EUR(350))
         );
     }
+
+    public function testMaxInit()
```
Comment (sagikazarmark) [inline tests/MoneyTest.php]: Thumb rule: everything, that is not functional nature test should go to specs.

File: src/Number.php (hunk 1 above)
Comment (frederikbosch) [inline src/Number.php]: Exactly my thoughts, I merged it because I was happy on the API. And actually, I thought this was pretty clever ;).

Comment (sagikazarmark) [inline src/Number.php]: Yeah, I agree, quite clever. :smile:

File: tests/MoneyTest.php (hunk 2 above)
Comment (frederikbosch) [inline tests/MoneyTest.php]: @sagikazarmark I was doing that, was fighting with it actually because I got errors that I was not able to fix quickly. Decided to leave it. My bad.
