### PR TITLE
throw for currencies that is not bitcoin

### LINKED ISSUE #295: Bitcoin currency repository should throw an exception when currency is unkown

### PR DESCRIPTION
**Pull request by frederikbosch**
Fixes #295

### CODE REVIEW

File: src/Currencies/BitcoinCurrencies.php [hunk 1]
```diff
@@ -26,6 +27,10 @@ public function contains(Currency $currency)
      */
     public function subunitFor(Currency $currency)
     {
+        if ($currency->getCode() !== self::CODE) {
+            throw new UnknownCurrencyException($currency->getCode().' cannot be found within BitcoinCurrencies');
```
Comment (sagikazarmark) [inline src/Currencies/BitcoinCurrencies.php]: I would rather say "XXX is not bitcoin and is not supported by this currency repository"

**Comment by frederikbosch** [comment]
Ok, will push that directly to master.

File: src/Currencies/BitcoinCurrencies.php (hunk 1 above)
Comment (frederikbosch) [inline src/Currencies/BitcoinCurrencies.php]: Done.
